'use strict';
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
const {startSuite}=require('../lib/harness');
(async()=>{
  const suite=await startSuite({extraRoutes:{'**/v2/lib/supabase-js.min.js':{body:fs.readFileSync(path.join(__dirname,'fixtures/product-workflow-db.js'),'utf8')}}});
  try{
    const {page,errors}=await suite.newPage();
    page.on('dialog',d=>d.accept());
    await page.goto(suite.BASE+'/v3/product-workflow.html');
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Choose a source'));
    assert.equal(await page.locator('.silo-sidebar a[href^="/v3/product-workflow"]').count(),0);
    await page.fill('#source-term','Practice');await page.click('#source-search button');
    await page.locator('#source-results button').click();
    assert.equal(await page.inputValue('#f-design_intent'),'Wear it every day');
    assert.equal(await page.locator('#lines tr').count(),2);
    assert.equal(await page.locator('#panel-overview').isVisible(),true);
    assert.equal(await page.locator('#panel-buy').isVisible(),false);
    assert.equal(await page.locator('#artwork').innerText().then(t=>t.includes('No reference artwork')),true);
    assert.equal(await page.evaluate(()=>window.__pw.calls.filter(c=>c.name==='save_product_workflow_brief').length),0);
    if (process.env.STUDIO_SCREENSHOTS) {
      fs.mkdirSync(process.env.STUDIO_SCREENSHOTS,{recursive:true});
      await page.locator('.silo-main').evaluate(el=>{el.scrollTop=0;});
      await page.waitForTimeout(350);
      await page.locator('.silo-main').evaluate(el=>{el.scrollTop=0;});
      await page.screenshot({path:path.join(process.env.STUDIO_SCREENSHOTS,'desktop.png'),fullPage:true});
    }
    await page.click('#tab-creative');await page.fill('#f-creative_dos','Keep the graphic compact');
    await page.click('#tab-buy');assert.equal(await page.locator('#lines').isVisible(),true);
    await page.click('#tab-overview');assert.equal(await page.inputValue('#f-creative_dos'),'Keep the graphic compact');
    await page.evaluate(()=>{window.__pw.failSave=true;});
    await page.click('#save');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Response lost'));
    assert.equal(await page.inputValue('#f-title'),'Practice tee');
    await page.click('#save');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Draft saved.');
    assert.equal(await page.evaluate(()=>window.__pw.tables.product_workflow_briefs.length),1);
    await page.fill('#source-term','Practice');await page.click('#source-search button');await page.locator('#source-results button').click();
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Continued the saved brief'));
    assert.equal(await page.evaluate(()=>window.__pw.tables.product_workflow_briefs.length),1);
    assert.equal(await page.inputValue('#f-creative_dos'),'Keep the graphic compact');
    await page.click('#another-brief');
    assert.equal(await page.locator('#brief-status').innerText(),'draft · unsaved');
    assert.equal(await page.evaluate(()=>window.__pw.tables.product_workflow_briefs.length),1);
    await page.locator('#source-results button').click();
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Continued the saved brief'));
    await page.click('#review');await page.waitForFunction(()=>document.querySelector('#brief-status').textContent.startsWith('reviewed'));
    assert.equal(await page.locator('#f-title').isDisabled(),true);
    await page.evaluate(()=>{window.__pw.failPipeline=true;});
    await page.click('#create-po');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Pipeline sync needs retry'));
    assert.equal(await page.locator('#outputs a[href*="po_id=PO1"]').count(),1);
    assert.equal(await page.locator('#create-po').isVisible(),false);
    await page.evaluate(()=>{window.__pw.failPipeline=false;});
    await page.click('#sync-pipeline');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Pipeline is in sync'));
    assert.equal(await page.evaluate(()=>window.__pw.tables.product_tracker[0].expected_units),100);
    assert.equal(await page.evaluate(()=>window.__pw.tables.po_headers.length),1);
    await page.fill('#handoff-date','2026-11-12');await page.click('#create-launch');
    await page.waitForSelector('#outputs a[href*="launch=LAUNCH1"]');
    const calls=await page.evaluate(()=>window.__pw.calls.filter(x=>x.name==='handoff_product_workflow_brief'));
    assert.equal(calls[1].args.p_launch_date,'2026-11-12');assert.equal(calls[1].args.p_company,'C1');
    await page.selectOption('#source-kind','restock');await page.fill('#source-term','Catalog');await page.click('#source-search button');await page.locator('#source-results button').click();
    await page.click('#tab-overview');await page.locator('#overview-edit').evaluate(el=>{el.open=true;});await page.fill('#f-design_intent','Keep the tee available');await page.click('#tab-buy');await page.click('#refresh-basis');
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Basis refreshed'));
    assert.equal(await page.locator('#use-suggestion').isEnabled(),true);
    await page.click('#use-suggestion');assert.equal(await page.locator('#lines input[data-key="qty"]').first().inputValue(),'750');
    assert.equal(await page.locator('#lines tr').count(),2);
    assert.equal(await page.locator('#lines input[data-key="qty"]').nth(1).inputValue(),'0');
    assert.match(await page.locator('#restock-basis').innerText(),/TEE-S/);
    await page.fill('#f-cover_days','30');assert.equal(await page.locator('#use-suggestion').isDisabled(),true);
    await page.click('#refresh-basis');await page.waitForFunction(()=>!document.querySelector('#use-suggestion').disabled);
    await page.click('#use-suggestion');assert.equal(await page.locator('#lines input[data-key="qty"]').first().inputValue(),'450');
    await page.click('#save');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Draft saved.');
    const spread=await page.evaluate(()=>window.__pw.tables.product_workflow_briefs.find(b=>b.source_kind==='restock'));
    assert.equal(spread.content.lines.length,2);assert.equal(spread.content.lines[1].qty,0);assert.equal(spread.content.lines[0].product_master_id,'P1');
    await page.click('#source-search button');await page.locator('#source-results button').click();
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Continued the saved brief'));
    assert.equal(await page.locator('#lines tr').count(),2);
    if(process.env.STUDIO_SCREENSHOTS) { await page.locator('#restock-basis').scrollIntoViewIfNeeded(); await page.screenshot({path:path.join(process.env.STUDIO_SCREENSHOTS,'spread-desktop.png'),fullPage:true}); }
    await page.setViewportSize({width:390,height:844});
    await page.waitForFunction(()=>document.querySelector('.silo-sidebar').getBoundingClientRect().right<=0);
    await page.locator('[data-silo-action="nav-toggle"]').click();
    await page.waitForFunction(()=>document.querySelector('#silo-app').classList.contains('silo-nav-open'));
    await page.keyboard.press('Escape');
    await page.waitForFunction(()=>!document.querySelector('#silo-app').classList.contains('silo-nav-open'));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile page does not overflow');
    assert.equal(await page.locator('#source-rail').isVisible(),false);
    await page.click('#browse-toggle');assert.equal(await page.locator('#source-rail').isVisible(),true);
    await page.click('#browse-toggle');
    if (process.env.STUDIO_SCREENSHOTS) { await page.locator('#lines').scrollIntoViewIfNeeded(); await page.screenshot({path:path.join(process.env.STUDIO_SCREENSHOTS,'mobile.png'),fullPage:true}); }
    assert.deepEqual(errors,[]);
    const viewer=await suite.newPage();
    await viewer.page.addInitScript(()=>{window.__pwViewer=true;});
    await viewer.page.goto(suite.BASE+'/v3/product-workflow.html');
    await viewer.page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Read-only'));
    await viewer.page.selectOption('#source-kind','idea');await viewer.page.click('#source-search button');
    assert.equal(await viewer.page.locator('#save').isDisabled(),true);
    assert.equal(await viewer.page.locator('#review').isDisabled(),true);
    const missing=await suite.newPage();
    await missing.page.addInitScript(()=>{window.__pwMissing=true;});
    await missing.page.goto(suite.BASE+'/v3/product-workflow.html');
    await missing.page.waitForFunction(()=>document.querySelector('#status').textContent.includes('needs the product workflow migration'));
    assert.deepEqual(viewer.errors,[]);assert.deepEqual(missing.errors,[]);
    const linked=await suite.newPage();
    await linked.page.goto(suite.BASE+'/v3/product-workflow.html?concept=CPT1');
    await linked.page.waitForSelector('#editor:not([hidden])');
    assert.equal(await linked.page.inputValue('#f-title'),'Practice tee');
    assert.equal(await linked.page.evaluate(()=>window.__pw.tables.product_workflow_briefs.length),0);
    await linked.page.click('#tab-overview');await linked.page.keyboard.press('ArrowRight');
    assert.equal(await linked.page.locator('#tab-creative').getAttribute('aria-selected'),'true');
    await linked.page.route('https://studio-fixture.test/reference.svg',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#e5edf4"/><text x="20" y="100">Reference artwork</text></svg>'}));
    await linked.page.evaluate(()=>{window.__pw.tables.product_concepts[0].reference_image_urls=['javascript:alert(1)','https://studio-fixture.test/reference.svg'];});
    linked.page.on('dialog',d=>d.accept());
    await linked.page.fill('#source-term','Practice');await linked.page.click('#source-search button');await linked.page.locator('#source-results button').click();
    await linked.page.waitForFunction(()=>document.querySelector('#artwork .pw-hero')?.naturalWidth>0);
    assert.equal(await linked.page.locator('#artwork a[href^="javascript:"]').count(),0);
    assert.equal(await linked.page.locator('#artwork .pw-artwork-links a').count(),1);
    const inaccessible=await suite.newPage();
    await inaccessible.page.goto(suite.BASE+'/v3/product-workflow.html?concept=FOREIGN');
    await inaccessible.page.waitForFunction(()=>document.querySelector('#status').textContent.includes('unavailable in the active company'));
    assert.equal(await inaccessible.page.locator('#editor').isVisible(),false);
    assert.deepEqual(linked.errors,[]);assert.deepEqual(inaccessible.errors,[]);
    console.log('Product Studio tabs, unsaved edits, source resume, empty artwork; real preview page: preset → retry save → review → PO → Pipeline failure/retry → launch; restock recalculation and mobile layout passed.');
  }finally{await suite.close();}
})().catch(e=>{console.error(e);process.exit(1);});
