'use strict';
const assert = require('assert/strict');
const { startSuite, inspectorTab, PERSIST_FAKE_DB } = require('../lib/harness');
(async () => {
  const suite = await startSuite();
  try {
    const { page, errors } = await suite.newPage();
    await page.addInitScript(PERSIST_FAKE_DB);
    await page.goto(`${suite.BASE}/v3/dashboard.html?id=D1&edit=1`);
    await page.waitForSelector('#btnAddWidget:not([hidden])');
    await page.click('#btnAddWidget');
    await page.click('.v3-report-card:has-text("Sales by product, one store")');
    await page.waitForSelector('.dw');
    await inspectorTab(page, 'visual');
    await page.click('label:has(input[name="visualType"][value="table"])');
    await page.selectOption('#inspTableLayout', 'summary');
    await page.waitForSelector('.dw-summary-card');
    await page.selectOption('#inspSummaryHeading', 'product_title');
    await page.click('#btnCloseInspector');
    await page.click('#btnSave');
    await page.waitForFunction(() => !document.querySelector('#dirtyPill').offsetParent);
    const geometry = () => page.evaluate(() => JSON.stringify([...window.__siloDashboard.runtime.layout()]));
    const before = await geometry();
    const calls = await page.evaluate(() => window.__FAKE_DB__.rpcCalls.length);
    await page.click('#btnReportView');
    await page.waitForSelector('body.is-report-view');
    assert.equal(await geometry(), before, 'report layout must not change grid nodes');
    assert.equal(await page.evaluate(() => window.__FAKE_DB__.rpcCalls.length), calls, 'entering report does not query');
    assert.equal(await page.locator('.silo-sidebar').isVisible(), false);
    assert.equal(await page.locator('#btnPrintReport').isVisible(), true);
    const overflow = await page.locator('.dw-body').first().evaluate(e => e.scrollHeight > e.clientHeight + 2);
    assert.equal(overflow, false, 'report summaries expand instead of clipping');
    // The live SQL path still takes the declared filter. Text is not a saved answer.
    await page.fill('#slicer_store', 'Seattle');
    await page.press('#slicer_store', 'Enter');
    await page.waitForFunction(() => window.__FAKE_DB__.rpcCalls.some(c => c.args?.query?.includes("'Seattle'")));
    await page.reload();
    await page.waitForSelector('body.is-report-view .dw-summary-card');
    assert.equal(await page.locator('#inspTableLayout').count(), 0, 'inspector closed on reload');
    await page.evaluate(() => { window.print = () => { window.__PRINT_CALLED__ = true; }; });
    await page.click('#btnPrintReport');
    assert.ok(await page.evaluate(() => window.__PRINT_CALLED__));
    await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')));
    await page.emulateMedia({ media: 'print' });
    assert.equal(await page.locator('.dw-table-tools').isVisible(), false);
    assert.equal(await page.locator('#filterChips').isVisible(), true, 'printed copy keeps applied filters');
    await page.emulateMedia({ media: 'screen' });
    await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    assert.ok(await page.locator('body').evaluate(e => e.classList.contains('is-report-view')));
    if (process.env.V3_TEST_SCREENSHOTS) await page.screenshot({ path: process.env.V3_TEST_SCREENSHOTS, fullPage: true });
    await page.click('#btnEdit');
    assert.equal(await page.locator('body').evaluate(e => e.classList.contains('is-report-view')), false);
    assert.equal(await geometry(), before, 'exit and reload preserve desktop geometry');
    await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')));
    await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    assert.ok(await page.locator('#btnSave').isVisible(), 'browser printing restores edit mode');
    await page.click('#btnReportView');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(300);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2), 'report fits phone');
    assert.deepEqual(errors, []);
    console.log('Report view: persistence, filters, print, geometry and mobile passed');
  } finally { await suite.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
