'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const root = path.resolve(__dirname,'../../..');
const g = { window:{} }; vm.createContext(g);
let source=fs.readFileSync(path.join(root,'v3/product-workflow-model.js'),'utf8');
if(process.env.MUTATE==='denominator') source=source.replace('units / 90','units / (lead + cover)');
vm.runInContext(source,g);
const M=g.window.SiloProductWorkflow;
const preset=M.preset('concept',{title:'A tee',concept_summary:'Baseball',suggested_size_breakdown:{S:40,M:60},suggested_marketing_copy:'Draft',suggested_launch_date:'2026-11-01',economics:{unit_cost:5,msrp:20}});
assert.equal(preset.lines.length,2);assert.equal(preset.lines[0].qty,40);assert.equal(preset.draft_copy,'Draft');assert.equal(preset.approved_copy,undefined);
assert.equal(M.preset('product',{product_title:'Tee',sku:'ABC',variant_title:'L'}).lines[0].qty,'');
assert.equal(M.preset('idea').title,'');
const now=Date.parse('2026-09-26T12:00:00Z');
const r={lead_days:30,cover_days:60,safety_units:10,basis:{units_90d:900,on_hand:100,incoming_units:50,horizon_days:90,sales_names:1,stock_as_of:'2026-09-26T00:00:00Z',observed_at:'2026-09-26T10:00:00Z'}};
assert.equal(M.restock(r,now).qty,760);assert.equal(M.restock({...r,cover_days:30,basis:{...r.basis,horizon_days:60}},now).qty,460);
assert.equal(M.restock(r,now).cover,10);
assert.equal(M.restock({...r,lead_days:''},now).qty,null);
assert.equal(M.restock({...r,cover_days:120},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,units_90d:null}},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,on_hand:-1}},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,on_hand:5000}},now).qty,0);
assert.ok(M.restock({...r,basis:{...r.basis,sales_names:2,uncertain_po_lines:1,stock_as_of:'2026-01-01'}},now).warnings.length>=3);
assert.throws(()=>M.validate({title:'X',design_intent:'Y',lines:[{qty:10}],restock:{basis:null}},'restock',true),/Explain/);
assert.equal(M.validate({title:'X',design_intent:'Y',decision_note:'Manual demand review',lines:[{qty:10}],restock:{basis:null}},'restock',true).title,'X');
for(const file of ['v2/nav-config.js','v2/product-concepts.html','v2/po-builder.html','v2/launch-calendar.html']) assert.ok(!fs.readFileSync(path.join(root,file),'utf8').includes('product-workflow.html'),file+' remains unpromoted');
console.log('Product presets, restock math, unknown evidence, review overrides and direct-link isolation passed.');
