'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const root = path.resolve(__dirname,'../../..');
const g = { window:{} }; vm.createContext(g);
let source=fs.readFileSync(path.join(root,'v3/product-workflow-model.js'),'utf8');
if(process.env.MUTATE==='denominator') source=source.replace('units / 90','units / (lead + cover)');
vm.runInContext(source,g);
const M=g.window.SiloProductWorkflow;
const preset=M.preset('concept',{title:'A tee',concept_summary:'Baseball',suggested_size_breakdown:{S:40,M:60},suggested_marketing_copy:'Draft',suggested_launch_date:'2026-11-01',economics:{unit_cost:5,msrp:20}});
assert.equal(preset.lines.length,2);assert.equal(preset.lines[0].qty,40);assert.equal(preset.draft_copy,'Draft');assert.equal(preset.approved_copy,undefined);
assert.equal(M.preset('product',{product_title:'Tee',sku:'ABC',variant_title:'L'}).lines[0].qty,'');
assert.equal(M.preset('idea').title,'');
const now=Date.parse('2026-09-26T12:00:00Z');
const r={lead_days:30,cover_days:60,safety_units:10,basis:{units_90d:900,on_hand:100,incoming_units:50,horizon_days:90,sales_names:1,stock_as_of:'2026-09-26T00:00:00Z',observed_at:'2026-09-26T10:00:00Z'}};
assert.equal(M.restock(r,now).qty,760);assert.equal(M.restock({...r,cover_days:30,basis:{...r.basis,horizon_days:60}},now).qty,460);
assert.equal(M.restock(r,now).cover,10);
assert.equal(M.restock({...r,lead_days:''},now).qty,null);
assert.equal(M.restock({...r,cover_days:120},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,units_90d:null}},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,on_hand:-1}},now).qty,null);
assert.equal(M.restock({...r,basis:{...r.basis,on_hand:5000}},now).qty,0);
assert.ok(M.restock({...r,basis:{...r.basis,sales_names:2,uncertain_po_lines:1,stock_as_of:'2026-01-01'}},now).warnings.length>=3);
assert.throws(()=>M.validate({title:'X',design_intent:'Y',lines:[{qty:10}],restock:{basis:null}},'restock',true),/Explain/);
assert.equal(M.validate({title:'X',design_intent:'Y',decision_note:'Manual demand review',lines:[{qty:10}],restock:{basis:null}},'restock',true).title,'X');
const spread=M.preset('restock',{product_title:'Tee',catalog_group:{shop_domain:'store.test',shopify_product_id:'10'},variants:[{id:'M',sku:'TEE-M',variant_title:'M'},{id:'S',sku:'TEE-S',variant_title:'S'}]});
assert.equal(spread.lines.length,2);assert.equal(spread.catalog_scope,'product');assert.equal(spread.lines[0].product_master_id,'M');
spread.restock={lead_days:0,cover_days:90,safety_units:0,bases:[{...r.basis,product_id:'M',units_90d:900,on_hand:100,incoming_units:0},{...r.basis,product_id:'S',units_90d:90,on_hand:1000,incoming_units:0}]};
assert.equal(M.spreadRestock(spread)[0].qty,800);assert.equal(M.spreadRestock(spread)[1].qty,0);
spread.design_intent='Keep sizes available';assert.throws(()=>M.validate(spread,'restock',true),/Choose units/);
spread.lines[0].qty=800;spread.lines[1].qty=0;spread.restock.bases[1].units_90d=null;
assert.equal(M.spreadRestock(spread)[1].qty,null);assert.throws(()=>M.validate(spread,'restock',true),/Explain/);
spread.decision_note='Deliberately skip the unknown small size';assert.equal(M.validate(spread,'restock',true).lines.length,2);
// Promoted 2026-09-30: Product Studio is the Purchasing destination and the
// old Product Concepts URL forwards to it (keeping ?concept=).
// Hidden from the menu 2026-10-05: the row stays in the file, commented out, so restoring it is one line.
assert.match(fs.readFileSync(path.join(root,'v2/nav-config.js'),'utf8'),/^\s*\/\/ \{ id: 'purchasing\/product-studio'[^\n]*href: '\/v3\/product-workflow\.html'/m);
const legacy=fs.readFileSync(path.join(root,'v2/product-concepts.html'),'utf8');
assert.match(legacy,/location\.replace\('\/v3\/product-workflow\.html'/);assert.match(legacy,/next\.set\('concept'/);
// Ready for PO: an Ask SILO proposal never arrives confirmed.
const noSizes=M.preset('concept',{title:'Bat Bros Youth Hoodie',suggested_qty:1400,suggested_product_type:'Youth Sweatshirt',suggested_factory_id:'F1'});
assert.equal(noSizes.lines.length,0,'no unsized line is invented for a concept without sizes');
assert.equal(noSizes.po_readiness.total_qty,1400);assert.equal(noSizes.po_readiness.size_mode,null);assert.equal(noSizes.po_readiness.range_confirmed,false);
const oneSize=M.preset('concept',{title:'Youth Cap',suggested_size_breakdown:{'One Size (adjustable snapback)':1800},suggested_qty:1800,suggested_factory_id:'F1'});
assert.equal(oneSize.po_readiness.size_mode,null,'one populated size is not assumed to be one size');
const issues=c=>JSON.parse(JSON.stringify(M.readinessIssues(c,{factoryIds:['F1']})));
assert.deepEqual(issues(oneSize),['Choose a product type','Choose whether the product is sized or one size','Confirm the size/variant range and quantities']);
const confirmed=c=>({...c,po_readiness:{...c.po_readiness,range_confirmed:true,confirmed_lines:M.confirmedLines(c.lines)}});
assert.deepEqual(issues(confirmed({...oneSize,product_type:'Hats',po_readiness:{...oneSize.po_readiness,size_mode:'one_size'}})),[]);
assert.deepEqual(issues(confirmed({...preset,factory_id:'F1',product_type:'Tees',po_readiness:{size_mode:'sized',total_qty:90}})),['Sizes total 100 units but the confirmed total is 90']);
const stale={...confirmed({...preset,factory_id:'F1',product_type:'Tees',po_readiness:{size_mode:'sized',total_qty:100}})};stale.lines=[{size:'S',qty:40},{size:'M',qty:61}];stale.po_readiness.total_qty=101;
assert.deepEqual(issues(stale),['Confirm the size/variant range and quantities'],'a confirmation of different lines is not a confirmation');
assert.deepEqual(JSON.parse(JSON.stringify(M.readinessIssues(oneSize,{factoryIds:['F1'],isCollection:true}))),['This is a collection. Mark each product in it ready for PO separately']);
console.log('Product presets, restock math, unknown evidence, review overrides, Ready for PO checklist and promotion passed.');
