-- Minimal upstream schema; real Product Workflow and On Deck migrations are applied.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; grant usage on schema public,auth to authenticated,anon,service_role;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key);
create table public.entities(id uuid primary key);
create table public.profiles(id uuid primary key,role text,is_active boolean default true);
create table public.entity_memberships(entity_id uuid,user_id uuid,role text);
create function public.active_company_id() returns uuid language sql stable as $$select nullif(current_setting('test.company',true),'')::uuid$$;
create function public.po_builder_can_write() returns boolean language sql stable security definer as $$select coalesce(current_setting('test.purchasing',true),'true')<>'false'$$;
create function public.can_approve_seo_tasks() returns boolean language sql stable security definer as $$select coalesce(current_setting('test.seo',true),'true')<>'false'$$;
create function public.silo_business_today() returns date language sql stable as $$select current_date$$;
create function public.silo_business_yesterday() returns date language sql stable as $$select current_date-1$$;
create function public.silo_business_timezone() returns text language sql stable as $$select 'UTC'::text$$;
create function public.silo_company_timezone(uuid) returns text language sql stable as $$select 'UTC'::text$$;
create function public.attach_stamp_company_entity_id_triggers() returns void language sql as $$select$$;
create table public.products_master(id uuid primary key,company_entity_id uuid,sku text,product_title text,product_type text,variant_title text,updated_at timestamptz default now(),reorderable boolean,is_evergreen boolean,is_seasonal boolean,is_drop boolean,is_discontinued boolean,lead_time_days integer,unit_cost numeric,msrp numeric,gross_margin_target numeric,peak_start_month integer,peak_end_month integer);
create table public.shopify_product_skus(company_entity_id uuid,shop_domain text,shopify_product_id text,shopify_variant_id text,sku text,product_title text,variant_title text,last_seen_at timestamptz default now());
create table public.product_concepts(id uuid primary key,company_entity_id uuid,title text,status text,suggested_factory_id uuid,parent_concept_id uuid,updated_at timestamptz default now());
create table public.factories(id uuid primary key,company_entity_id uuid,factory_name text);
create function public.generate_next_po_name(uuid) returns text language sql as $$select 'TEST-PO'::text$$;
create table public.po_headers(id uuid primary key default gen_random_uuid(),company_entity_id uuid,status text,expected_arrival_date date,updated_at timestamptz default now(),po_name text,factory_id uuid,order_date date,is_new_product_po boolean,created_by uuid,internal_notes text);
create table public.po_lines(id uuid primary key default gen_random_uuid(),company_entity_id uuid,po_header_id uuid,sku_snapshot text,qty integer,updated_at timestamptz default now(),unit_cost numeric,retail_price numeric,product_master_id uuid,source_concept_id uuid,title_snapshot text,product_type_snapshot text,variant_title_snapshot text,line_notes text);
create table public.po_concept_links(company_entity_id uuid,po_header_id uuid,concept_id uuid,created_by uuid);
create table public.sales_by_day(company_entity_id uuid,sku text,day_date date,total_quantity_sold integer,total_net_sales numeric,product_name text,synced_at timestamptz default now());
create table public.inventory_on_hand_current_mv(company_entity_id uuid,variant_sku text,total_available_quantity integer,snapshot_at timestamptz,shop_domain text);
create view public.inventory_on_hand_current_v as select * from public.inventory_on_hand_current_mv where company_entity_id=public.active_company_id();
create table public.sync_jobs(company_entity_id uuid,job_type text,status text,finished_at timestamptz);
create table public.launch_calendar(id uuid primary key default gen_random_uuid(),company_entity_id uuid,title text,launch_date date,design_intent text,audience text,marketing_angle text,product_callouts text,copy_dos text,copy_donts text,status text,updated_at timestamptz default now(),time_zone text,created_by uuid,linked_po_id uuid,linked_product_id uuid,source_concept_id uuid,special_callouts text,creative_dos text,creative_donts text,notes text,products_unknown_at timestamptz,products_unknown_note text);
create table public.launch_product_readiness(company_entity_id uuid,launch_id uuid,product_title text,readiness_status text,updated_at timestamptz default now(),product_type text,created_by uuid,notes text);
create table public.launch_tasks(id uuid primary key default gen_random_uuid(),company_entity_id uuid,launch_id uuid,task_title text,task_type text,status text,notes text,created_by uuid,is_private boolean default false,updated_at timestamptz default now());
create table public.search_console_page_daily(company_entity_id uuid,connection_id uuid,site_url text,day_date date,page text,clicks numeric,impressions numeric,position numeric,synced_at timestamptz default now());
create table public.page_inspections(company_entity_id uuid,requested_url text,final_url text,title text,meta_description text,h1 text,word_count integer,http_status integer,fetch_error text,fetched_at timestamptz default now());
create table public.meta_ad_performance_daily(company_entity_id uuid,ad_id text,ad_name text,campaign_name text,day_date date,spend numeric,impressions numeric,clicks numeric,conversions numeric,conversion_value numeric,thruplays numeric,leads numeric,synced_at timestamptz default now());
create table public.meta_ad_creatives(company_entity_id uuid,ad_id text,body text,title text,link_url text,effective_status text,synced_at timestamptz default now());
create function public.meta_campaign_group(text) returns text language sql immutable as $$select lower($1)$$;
create table public.seo_projects(id uuid primary key default gen_random_uuid(),company_entity_id uuid,name text,status text,evidence_note text,created_by uuid);
create table public.seo_tasks(id uuid primary key default gen_random_uuid(),company_entity_id uuid,project_id uuid,title text,target_type text,target_url text,rationale text,proposed_title text,proposed_meta_description text,proposed_body text,approval_status text,created_by uuid);
create table public.ad_ideas(id uuid primary key default gen_random_uuid(),company_entity_id uuid,title text,hook text,angle text,body_draft text,objective text,baseline_ad_ids text[],baseline_snapshot jsonb,source text,created_by uuid,status text);
grant select on all tables in schema public to authenticated;
grant all on all tables in schema public to service_role;
-- Supabase defaults must not make new preparation writers client-callable.
alter default privileges in schema public grant all on tables to anon,authenticated,service_role;
alter default privileges in schema public grant execute on functions to anon,authenticated,service_role;
