import assert from 'node:assert/strict';
import {summarize,journeyFlow,escapeHtml,platformMark,loadRows} from '../../v2/silo-attribution-report.js';
const controls=[{day:'2026-09-01',currency:'USD',shop_timezone:'America/Los_Angeles',net_cents:100,total_cents:120,extracted_at:'snapshot'}];
const allocation={channel:'Redo Email',window_days:30,visit_id:'r',introduced_channel:'Meta Ads',introduced_visit_id:'m',assisting_channels:['Meta Ads']};
const rows=[{...controls[0],order_id:'1',order_name:'#1',window_days:30,channel:'Redo Email',allocation,net_cents:100,total_cents:120,evidence_fetched_at:'e'}];
let result=summarize(rows,controls,30);
assert.equal(result.net,100);assert.equal(result.channels.find(c=>c.channel==='Meta Ads').net_cents,0);assert.equal(result.channels.find(c=>c.channel==='Meta Ads').assisted_orders,1);
assert.throws(()=>summarize([...rows,...rows],controls,30),/Duplicate/);
assert.throws(()=>summarize(rows,controls,7),/Mixed/);
assert.throws(()=>summarize(rows,[{...controls[0],net_cents:101}],30),/reconciliation/);
assert.throws(()=>summarize(rows,[{...controls[0],extracted_at:'new'}],30),/reconciliation/);
assert.throws(()=>summarize(rows,[],30),/No published/);
result=summarize([...rows,{...rows[0],day:'2026-09-02',net_cents:-100,total_cents:-120}],[...controls,{...controls[0],day:'2026-09-02',net_cents:-100,total_cents:-120}],30);
assert.equal(result.net,0);assert.equal(result.orders.length,1);assert.equal(result.orders[0].net_cents,0);
assert.equal(escapeHtml('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');
assert.ok(platformMark('Meta Ads').includes('#icon-meta'));assert.ok(platformMark('Unknown').includes('attr-fallback'));
const visit=(id,source,medium,time)=>({id,occurredAt:time,utmParameters:{source,medium,campaign:'<script>bad</script>'}});
const m=visit('m','facebook','paid','2026-09-01T08:00:00Z'),r=visit('r','redo','email','2026-09-01T09:00:00Z');
const e={order:{name:'#1',createdAt:'2026-09-01T10:00:00Z',customerJourneySummary:{firstVisit:m,lastVisit:r,moments:{nodes:[m,r]}}}};
const flow=journeyFlow(e,allocation,'America/Los_Angeles','USD',100);
assert.ok(flow.includes('<ol'));assert.ok(!flow.includes('<table'));assert.ok(flow.indexOf('Meta Ads')<flow.indexOf('Redo Email'));assert.ok(flow.includes('Credited touch'));assert.ok(flow.includes('Introducing touch'));assert.ok(!flow.includes('<script>bad'));
const calls=[];
const tenant='00000000-0000-0000-0000-000000000001',store='00000000-0000-0000-0000-000000000002';
const db={rpc(name,args){assert.equal(name,'chat_run_readonly_query');assert.ok(args.query.includes(tenant)&&args.query.includes(store));return Promise.resolve({data:rows,error:null});},from(table){const q={table,filters:[]};const chain={select(){return chain;},eq(k,v){q.filters.push([k,v]);return chain;},gte(){return chain;},lte(){return chain;},order(){return chain;},range(){return chain;},then(resolve){calls.push(q);resolve({data:table==='shopify_attribution_days'?controls:rows,error:null});}};return chain;}};
assert.equal((await loadRows(db,tenant,store,'2026-09-01','2026-09-01',30)).net,100);
assert.ok(calls.every(q=>q.filters.some(([k,v])=>k==='company_entity_id'&&v===tenant)&&q.filters.some(([k,v])=>k==='connection_id'&&v===store)));
await assert.rejects(loadRows(db,tenant,store,'2026-09-01','2026-09-02',30),/not been backfilled/);
console.log('Attribution report: reconciliation, overlaps, reversals, escaped flow and tenant-scoped loader passed');
const old=visit('old','facebook','paid','2026-07-23T10:00:00Z');
const partial={order:{name:'#partial',createdAt:'2026-09-01T10:00:00Z',customerJourneySummary:{firstVisit:old,lastVisit:old,moments:{nodes:[old]}}}};
assert.ok(journeyFlow(partial,null,'UTC','USD',100,7).includes('Outside selected window'));
assert.ok(!journeyFlow(partial,null,'UTC','USD',100,60).includes('Outside selected window'));
const fallback={...allocation,channel:'Google Ads',assignment:'first_touch_fallback',visit_id:'',campaign:'<script>landing</script>',source:'google',medium:'paid'};
const missing={order:{name:'#fallback',createdAt:'2026-09-01T10:00:00Z',customerJourneySummary:null},raw:{landing_path:'/caps'}};
const fallbackFlow=journeyFlow(missing,fallback,'UTC','USD',100,30);
assert.ok(fallbackFlow.includes('Credited first-touch fallback'));assert.ok(fallbackFlow.includes('visit time unavailable'));assert.ok(fallbackFlow.includes('Source: google'));assert.ok(!fallbackFlow.includes('<script>landing'));
assert.ok(journeyFlow({order:{name:'#old',createdAt:null,customerJourneySummary:null}},null,'UTC','USD',-100,7).includes('Purchase time unavailable'));
