/** Source-only business context. This module never creates model assumptions. */
import { sourceTrendChart } from './charts.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const numeric=n=>Number.isFinite(n)?n:null;
const n=(v,compact=false)=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{notation:compact?'compact':'standard',maximumFractionDigits:compact?1:0}).format(v):'—';
const amount=(v,currency,compact=false)=>Number.isFinite(v)?`${currency==='USD'?'$':''}${n(v,compact)}${currency&&currency!=='USD'?` ${esc(currency)}`:''}`:'—';
const percent=v=>Number.isFinite(v)?`${v.toFixed(1)}%`:'—';
const latest=(rows=[])=>rows.slice().sort((a,b)=>(a.periodEnd||a.month||'').localeCompare(b.periodEnd||b.month||'')).at(-1)||{};
const metric=(source,label)=>source?.scopeFiltered?null:source?.metrics?.find(m=>m.label===label)?.value??null;
const caption=s=>`${s?.periodStart||'Start unknown'} → ${s?.periodEnd||'End unknown'} · ${s?.currency||'Currency not recorded'} · ${s?.basis||'Basis not stated'}`;
const kpi=(label,value,note)=>`<div class="uw-business-kpi"><div class="uw-kpi-label">${esc(label)}</div><div class="uw-kpi-value">${value}</div><div class="uw-kpi-note">${esc(note)}</div></div>`;
const table=(headers,rows,cls='')=>`<table class="uw-table ${cls}"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}" class="uw-missing">No source rows available</td></tr>`}</tbody></table>`;
const warning=text=>`<p class="uw-data-warning">${esc(text)}</p>`;
const meta=s=>[s?.error?`Read failed: ${s.error.message||s.error}`:'',s?.detailError?`Detail read failed: ${s.detailError.message}`:'',s?.historyError?`History read failed: ${s.historyError.message}`:''].filter(Boolean).map(warning).join('');
const knownSum=(rows,key)=>rows.length&&rows.every(r=>Number.isFinite(r[key]))?rows.reduce((t,r)=>t+r[key],0):null;

export function businessView(snapshot) {
  const sources=snapshot?.sources||{},pl=sources.profitAndLoss||{},bs=sources.balanceSheet||{},bank=sources.bank||{},inv=sources.inventory||{},po=sources.purchaseOrders||{},plan=sources.revenuePlan||{};
  const pRows=(pl.monthly||[]).slice(-12),bRows=(bs.monthly||[]).slice(-12),p=latest(pRows),b=latest(bRows);
  const revenue=pRows.length?numeric(p.revenue):metric(pl,'Income'),gross=pRows.length?numeric(p.grossProfit):metric(pl,'Gross profit');
  const margin=Number.isFinite(revenue)&&revenue!==0&&Number.isFinite(gross)?gross/revenue*100:null;
  const cash=bRows.length?numeric(b.bookCash):metric(bs,'Book bank balances'),liabilities=bRows.length?numeric(b.liabilities):metric(bs,'Total liabilities');
  const invRow=inv.rows?.[0]||{},units=metric(inv,'Reported on-hand units')??numeric(invRow.reported_units);
  const placed=po.placed||[],placedCount=Number.isFinite(po.placedCount)?po.placedCount:null,knownPlaced=knownSum(placed,'knownEstimatedCost');
  const period=p.periodStart&&p.periodEnd?`${p.periodStart}–${p.periodEnd}`:pl.selectedColumn?.periodStart?`${pl.selectedColumn.periodStart}–${pl.selectedColumn.periodEnd}`:`${pl.periodStart||'?'}–${pl.periodEnd||'?'}`;
  const kpis=kpi('Reported revenue',amount(revenue,pl.currency,true),period)+kpi('Gross margin',percent(margin),'Reported gross profit ÷ revenue')+kpi('Book bank balances',amount(cash,bs.currency,true),`QBO · ${b.periodEnd||bs.periodEnd||'date unknown'}`)+kpi('Total liabilities',amount(liabilities,bs.currency,true),'All liabilities · not total debt service')+kpi('Inventory on hand',n(units,true),'Reported units · current snapshot')+kpi('Placed PO cost · known',amount(knownPlaced,null,true),`${placedCount===null?'Unknown':placed.length} orders loaded · currency unrecorded`);
  const performance=`<p class="uw-source-caption">${esc(caption(pl.history||pl))}</p><div class="uw-source-chart">${sourceTrendChart(pRows.map(r=>({...r,month:r.periodEnd?.slice(0,7)})),[{key:'revenue',label:'Revenue',color:'var(--bcn-accent)'},{key:'grossProfit',label:'Gross profit',color:'var(--bcn-pos)'}],{bars:true,ariaLabel:'QBO monthly revenue and gross profit. Partial or missing months are not filled.'})}</div><div class="uw-legend uw-source-legend"><span><i class="uw-swatch uw-proposed"></i>Revenue</span><span><i class="uw-swatch uw-swatch-profit"></i>Gross profit</span><span>Latest margin ${percent(margin)}</span></div>${pRows.some(r=>!r.completeMonth)?warning('Partial calendar months are present; compare like-for-like periods.'):''}${meta(pl)}<details class="uw-disclosure" open><summary>Monthly reported figures <span>Revenue, margin and operating income</span></summary><div class="uw-table-wrap">${table(['Month end','Revenue','Gross profit','Gross margin','Operating income'],pRows.map(r=>`<tr><td>${esc(r.periodEnd)}${r.completeMonth?'':' *'}</td><td>${amount(r.revenue,r.currency||pl.currency)}</td><td>${amount(r.grossProfit,r.currency||pl.currency)}</td><td>${percent(r.grossMarginPct)}</td><td>${amount(r.operatingIncome,r.currency||pl.currency)}</td></tr>`))}</div></details>`;
  const liabilitiesRows=[['Accounts payable',b.accountsPayable],['Credit-card balances',b.creditCards],['Current liabilities',b.currentLiabilities],['Long-term liabilities',b.longTermLiabilities]];
  const bankRows=(bank.rows||[]).slice(0,3);
  const liquidity=`<p class="uw-source-caption">QBO as of ${esc(b.periodEnd||bs.periodEnd||'unknown')} · ${esc(bs.currency||'currency unknown')}</p><div class="uw-facts"><div><span class="uw-data-label">Assets</span><strong>${amount(bRows.length?numeric(b.assets):metric(bs,'Total assets'),bs.currency,true)}</strong></div><div><span class="uw-data-label">Liabilities</span><strong>${amount(liabilities,bs.currency,true)}</strong></div><div><span class="uw-data-label">Equity</span><strong>${amount(bRows.length?numeric(b.equity):metric(bs,'Total equity'),bs.currency,true)}</strong></div></div>${table(['Reported account group','Book balance'],liabilitiesRows.map(([label,value])=>`<tr><td>${label}</td><td>${amount(value,bs.currency)}</td></tr>`),'uw-mini-table')}${bRows.length>1?`<div class="uw-source-mini-chart">${sourceTrendChart(bRows.map(r=>({...r,month:r.periodEnd?.slice(0,7)})),[{key:'bookCash',label:'Book bank balances',color:'var(--bcn-accent)'},{key:'accountsPayable',label:'Accounts payable',color:'var(--bcn-warn)'}],{height:135,ariaLabel:'Book bank balances and accounts payable monthly trend'})}</div><div class="uw-legend uw-source-legend"><span><i class="uw-swatch uw-proposed"></i>Book cash</span><span><i class="uw-swatch" style="background:var(--bcn-warn)"></i>A/P</span></div>`:''}<p class="uw-source-caption">Bank feed · current balances, not verified unrestricted cash</p>${table(['Bank account','Current balance','As of'],bankRows.map(r=>`<tr><td>${esc(r.name||r.id)}<span class="uw-subcell">${esc(r.connection_status||'status unknown')} · ${esc(r.environment||'environment unknown')}</span></td><td>${amount(r.current_balance,r.iso_currency_code)}</td><td>${esc(r.balance_updated_at?.slice(0,10)||'Unknown')}</td></tr>`),'uw-mini-table')}${meta(bs)}${meta(bank)}`;
  const planRows=(plan.monthly||[]).filter(r=>Number.isFinite(r.plannedSales)||Number.isFinite(r.actualNetSales)).slice(-18);
  const upcoming=planRows.filter(r=>r.month>=(plan.businessDate||'9999-99').slice(0,7)&&Number.isFinite(r.plannedSales)).slice(0,3);
  const planning=`<p class="uw-source-caption">Active location/day sales plan · latest update ${esc(plan.plans?.[0]?.updatedAt?.slice(0,10)||'unknown')}</p><div class="uw-source-chart">${sourceTrendChart(planRows,[{key:'plannedSales',label:'Stored sales plan',color:'var(--bcn-ink-4)',dashed:true},{key:'actualNetSales',label:'Recorded net sales',color:'var(--bcn-accent)'}],{height:190,ariaLabel:'Stored sales plan and recorded net sales. Sales basis and currency require reconciliation.'})}</div><div class="uw-legend uw-source-legend"><span><i class="uw-swatch uw-swatch-plan"></i>Stored sales plan</span><span><i class="uw-swatch uw-proposed"></i>Recorded net sales</span></div>${warning('Plan sales basis and currency are not recorded. No validated variance or margin/cash forecast is inferred; QBO revenue and recorded sales have different scopes.')}${upcoming.length?table(['Upcoming plan','Stored sales','Planned units'],upcoming.map(r=>`<tr><td>${esc(r.month)}</td><td>${n(r.plannedSales)}</td><td>${n(r.projectedUnits)}</td></tr>`),'uw-mini-table'):''}<details class="uw-disclosure"><summary>Plan coverage & monthly figures</summary><div class="uw-table-wrap">${table(['Month','Plan sales','Recorded net sales','Plan days','Actual days','Matched days'],planRows.map(r=>`<tr><td>${esc(r.month)}</td><td>${n(r.plannedSales)}</td><td>${n(r.actualNetSales)}</td><td>${n(r.plannedDays)}</td><td>${n(r.actualDays)}</td><td>${n(r.matchedDays)}</td></tr>`))}</div><p class="uw-fine">${esc((plan.warnings||[]).join(' '))}</p></details>${meta(plan)}`;
  const groups=inv.byProductType||[],arrivals=po.arrivalMonths||[];
  const exposure=`<div class="uw-facts"><div><span class="uw-data-label">On-hand units</span><strong>${n(units,true)}</strong><small>${esc(inv.asOf?.slice(0,10)||'Snapshot date unknown')}</small></div><div><span class="uw-data-label">Placed orders</span><strong>${n(placedCount)}</strong><small>${po.placedTruncated?`Loaded subset of ${po.placedCount}`:'Visible placed statuses'}</small></div><div><span class="uw-data-label">Cost coverage</span><strong>${placedCount===null?'—':n(placed.filter(r=>r.costComplete===true).length)} / ${placedCount===null?'—':n(placed.length)}</strong><small>Fully costed orders</small></div></div>${table(['Inventory group','Units','Reported value'],groups.slice(0,4).map(r=>`<tr><td>${esc(r.productType||r.product_type||'Unclassified')}</td><td>${n(r.units??r.reported_units)}</td><td>${n(r.knownRecordedValue)}<span class="uw-subcell">${n(r.missingValueRows??r.missing_value_rows)} missing value rows</span></td></tr>`),'uw-mini-table')}${arrivals.length?table(['Expected arrival','Placed orders','Known cost'],arrivals.slice(0,4).map(r=>`<tr><td>${esc(r.month||'Undated')}</td><td>${n(r.orderCount??r.poCount)}</td><td>${n(r.knownEstimatedCost)}</td></tr>`),'uw-mini-table'):''}${warning('Inventory values are not eligible collateral. Known PO costs exclude incomplete costs and are not unpaid balances. Ageing and payment terms are not inferred.')}${meta(inv)}${meta(po)}`;
  const orderTable=list=>table(['Purchase order / supplier','Status','Expected arrival','Units','Known line cost','Cost coverage'],list.map(r=>`<tr><td>${esc(r.name||r.id)}<span class="uw-subcell">${esc('Supplier not in this source')}</span></td><td>${esc(r.status||'Unknown')}</td><td>${esc(r.arrivalDate||'Not recorded')}</td><td>${n(r.units)}</td><td>${n(r.knownEstimatedCost)}<span class="uw-subcell">Currency not recorded · not unpaid</span></td><td>${r.costComplete?'Complete cost fields':`${n(r.missingCostLines)} missing · ${n(r.zeroCostLines)} zero`}<span class="uw-subcell">${n(r.lineCount)} lines</span></td></tr>`));
  const orders=`<div class="uw-table-wrap">${orderTable(placed.slice(0,6))}</div>${placed.length>6?`<details class="uw-disclosure"><summary>All ${placed.length} loaded placed orders</summary><div class="uw-table-wrap">${orderTable(placed)}</div></details>`:''}<p class="uw-fine">${esc(po.placedTruncated?'Loaded rows are capped; this is incomplete coverage. ':'')}Read-only source records. Confirm payments already made, deposits, currency and payment timing below before including a cash use.</p>`;
  const liabilityOptions=(snapshot?.accountOptions||[]).filter(a=>['Credit Card','CreditCard','Other Current Liability','OtherCurrentLiability','Long Term Liability','LongTermLiability'].includes(a.accountType));
  const liabilityAccounts=table(['Book liability account','Account ID','Book balance','As of','Required P&I'],liabilityOptions.slice(0,8).map(a=>`<tr><td>${esc(a.label)}<span class="uw-subcell">${esc(a.accountType)} · classification requires review</span></td><td>${esc(a.accountId)}</td><td>${amount(a.balance,a.balanceCurrency)}</td><td>${esc(a.balanceAsOf||'Unknown')}</td><td>Not in QBO balance source</td></tr>`))+`<p class="uw-fine">${liabilityOptions.length>8?'First 8 account mappings shown; use the selector for all loaded accounts. ':''}Account-type metadata identifies book liability groups, not a confirmed facility register. Enter lender payment schedules separately.</p>`;
  return {kpis,performance,liquidity,planning,exposure,orders,liabilityAccounts};
}
