/** Local, dynamic facility editor. No source reads or writes. */
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createFacility(id,kind='loan',currency='') {
  return {id,name:'',kind,balanceSource:'account',accountId:'',manualBalance:null,balanceAsOf:'',balanceProvenance:'',currency,limit:null,borrowingBase:null,reserves:null,lenderAvailable:null,availabilityAsOf:'',availabilityProvenance:'',scheduleMode:'payments',monthlyPayment:null,monthlyPayments:{},scheduleComplete:false,scheduleProvenance:'',terms:{annualRatePct:null,frequency:'monthly',repayment:'amortizing',firstPaymentMonth:'',maturityMonth:'',amortizationMonths:null}};
}
export function facilityRegisterHtml({facilities,portfolio,money}) {
  if(!facilities.length)return '<div class="uw-facility-empty"><strong>Add the loans and credit lines already in place</strong><p>Match an imported account or document a lender balance, then review the remaining payments.</p></div>';
  return `<div class="uw-table-wrap"><table class="uw-table uw-facility-register"><thead><tr><th>Facility / evidence</th><th>Outstanding</th><th>Committed limit</th><th>Usable undrawn</th><th>Next modeled P&I</th><th>Schedule</th><th></th></tr></thead><tbody>${facilities.map(f=>{
    const r=portfolio?.facilities?.find(x=>x.id===f.id),next=r?.rows?.find(x=>Number.isFinite(x.payment)&&x.payment>0),available=r?.availability??null;
    return `<tr><td><strong>${esc(f.name||'Unnamed facility')}</strong><span class="uw-subcell">${({loc:'Credit line',loan:'Term loan'})[f.kind]||'Type not documented'} · ${({account:'Linked QBO account',manual:'Manual lender balance'})[f.balanceSource]||'Balance source missing'} · ${esc(r?.balanceAsOf||f.balanceAsOf||'as-of missing')}</span></td><td>${money(r?.comparable?r.balance:null)}<span class="uw-subcell">${esc(f.currency||'Currency unknown')}</span></td><td>${f.kind==='loc'?money(r?.committedLimit):'Not revolving'}</td><td>${f.kind==='loc'?money(available):'—'}</td><td>${money(next?.payment)}<span class="uw-subcell">${esc(next?.month||'Not established')}</span></td><td><span class="uw-tag ${r?.scheduleComplete?'uw-tag-ok':''}">${r?.scheduleComplete?'Reviewed':'Needs review'}</span><span class="uw-subcell">${f.scheduleMode==='terms'?esc(f.terms.maturityMonth||'No maturity'):f.scheduleMode==='payments'?'Documented P&I':'Method missing'}</span></td><td><button type="button" class="uw-text-link" data-edit-facility="${esc(f.id)}">Edit</button></td></tr>`;
  }).join('')}</tbody></table></div>`;
}
export function facilityEditorHtml({facilities,accountOptions,portfolio,months,money,openIds=[]}) {
  const input=(f,key,label,type='text',hint='',term=false)=>`<div><label class="uw-label">${label}</label><input class="bcn-field" type="${type}" ${type==='number'?'step="any"':''} maxlength="2000" data-facility="${esc(f.id)}" data-field="${key}" ${term?'data-term="true"':''} aria-label="${label} for ${esc(f.name||'facility')}" value="${esc((term?f.terms:f)[key]??'')}">${hint?`<small class="uw-field-hint">${hint}</small>`:''}</div>`;
  const select=(f,key,label,options,term=false)=>`<div><label class="uw-label">${label}</label><select class="bcn-field" data-facility="${esc(f.id)}" data-field="${key}" ${term?'data-term="true"':''} aria-label="${label} for ${esc(f.name||'facility')}">${[['','Choose…'],...options.filter(o=>o[0]!=='')].map(([v,t])=>`<option value="${esc(v)}" ${(term?f.terms:f)[key]===v?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`;
  return facilities.map(f=>{
    const r=portfolio?.facilities?.find(x=>x.id===f.id),account=accountOptions.find(a=>a.id===f.accountId),issues=r?.issues||r?.errors||[];
    const opts=[['','Match account by ID'],...accountOptions.map(a=>[a.id,`${a.label||a.accountId} · ${a.accountId}`])];if(f.accountId&&!account)opts.push([f.accountId,'Saved account unavailable · '+f.accountId]);
    return `<details class="uw-facility-edit" data-facility-panel="${esc(f.id)}" ${openIds.includes(f.id)?'open':''}><summary><span>${esc(f.name||'New '+(f.kind==='loc'?'credit line':'loan'))}</span><small>${f.kind==='loc'?'Limits, restrictions & payments':'Balance & remaining payments'}</small></summary><div class="uw-facility-edit-body"><div class="uw-form-grid uw-four">${input(f,'name','Facility / lender name')}${select(f,'kind','Facility type',[['loan','Term loan'],['loc','Credit line']])}${select(f,'balanceSource','Balance evidence',[['account','Linked QBO account'],['manual','Documented manual balance']])}${select(f,'currency','Facility currency',[['','Unknown'],['USD','USD'],['CAD','CAD'],['EUR','EUR'],['GBP','GBP']])}${f.balanceSource==='account'?select(f,'accountId','Read-only source account',opts)+`<div class="uw-linked-balance"><span class="uw-label">Imported outstanding balance</span><strong>${account&&Number.isFinite(account.balance)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(account.balance)+' '+esc(account.balanceCurrency||'currency unknown'):'—'}</strong><small>${esc(account?.balanceAsOf||'No matched balance')} · ${esc(account?.balanceCurrency||'Currency unknown')}</small></div>`:input(f,'manualBalance','Documented outstanding','number')+input(f,'balanceAsOf','Balance as of','date')+input(f,'balanceProvenance','Balance evidence')}
    </div>${f.kind==='loc'?`<h4>Credit access · lender inputs</h4><div class="uw-form-grid uw-four">${input(f,'limit','Committed limit','number')}${input(f,'borrowingBase','Borrowing base','number')}${input(f,'reserves','Reserves / restrictions','number')}${input(f,'lenderAvailable','Lender net available','number','Already net of draw and restrictions')}${input(f,'availabilityAsOf','Availability as of','date')}${input(f,'availabilityProvenance','Availability evidence')}</div><p class="uw-fine">Undrawn availability remains separate from cash. No credit line is automatically drawn. A documented lender net quote or both borrowing base and reserves are required.</p>`:''}
    <h4>Remaining payment schedule</h4><div class="uw-form-grid uw-four">${select(f,'scheduleMode','Schedule method',f.kind==='loc'?[['payments','Documented monthly P&I']]:[['payments','Documented monthly P&I'],['terms','Calculate from remaining terms']])}${f.scheduleMode==='payments'?input(f,'monthlyPayment','Baseline monthly P&I','number','Enter 0 explicitly for months with no payment; override due months below.'):input(f,'annualRatePct','Annual rate %','number','',true)+select(f,'frequency','Payment frequency',[['monthly','Monthly'],['quarterly','Quarterly'],['annual','Annual']],true)+select(f,'repayment','Repayment',[['amortizing','Amortizing'],['interest-only','Interest-only + balloon'],['balloon','Amortizing + balloon']],true)+input(f,'firstPaymentMonth','First due month','month','',true)+input(f,'maturityMonth','Final due month','month','',true)+(f.terms.repayment==='balloon'?input(f,'amortizationMonths','Remaining amortization months','number','',true):'')}${input(f,'scheduleProvenance','Payment evidence / assumptions')}</div>
    ${f.scheduleMode==='payments'?`<details class="uw-disclosure"><summary>Monthly P&I overrides <span>Include maturities, balloons and explicit no-payment months</span></summary><div class="uw-facility-months">${months.map(month=>`<label><span>${month}</span><input type="number" step="any" class="bcn-field" data-facility="${esc(f.id)}" data-payment-month="${month}" aria-label="${esc(f.name||'Facility')} P&I ${month}" value="${esc(f.monthlyPayments?.[month]??'')}" placeholder="Use baseline"></label>`).join('')}</div></details>`:'<p class="uw-fine">Uses the documented opening principal and a full regular interest interval before the first due month. No new cash inflow. Use documented payments for accrued interest, stub periods, fees or variable-rate schedules.</p>'}
    <label class="uw-checkbox"><input type="checkbox" data-facility="${esc(f.id)}" data-field="scheduleComplete" ${f.scheduleComplete?'checked':''}>I reviewed all required payments and maturities for this facility in the selected horizon</label>${issues.length?`<p class="uw-data-warning">${esc(issues.join(' '))}</p>`:''}<button type="button" class="uw-text-link uw-remove-facility" data-remove-facility="${esc(f.id)}">Remove facility</button></div></details>`;
  }).join('');
}
