const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function cashTimingEditorHtml(timing) {
  return `<div class="uw-timing-grid">${[['collections','Slower customer collections','Receipts already forecast from customers'],['inventory','Delayed inventory cash recovery','Receipts tied to delayed inventory sell-through']].map(([key,title,hint])=>{const row=timing[key],field=(name,label,type)=>`<div><label class="uw-label">${label}</label><input class="bcn-field" type="${type}" ${type==='number'?'step="any"':''} maxlength="2000" data-timing="${key}" data-field="${name}" aria-label="${label} for ${title}" value="${esc(row[name]??'')}"></div>`;return `<section class="uw-timing-card"><label class="uw-checkbox uw-timing-title"><input type="checkbox" data-timing="${key}" data-field="enabled" ${row.enabled?'checked':''}>${title}</label><p>${hint}. Enter cash amounts; no sales-to-cash assumption is inferred.</p>${row.enabled?`<div class="uw-form-grid">${field('baselineReceipts','Documented receipt pool','number')}${field('amount','Amount delayed','number')}${field('fromMonth','Original receipt month','month')}${field('toMonth','Delayed receipt month','month')}${field('sourceReference','Assumption / evidence','text')}</div><label class="uw-checkbox"><input type="checkbox" data-timing="${key}" data-field="reviewed" ${row.reviewed?'checked':''}>Already in my forecast, still collectible under this downside, and not counted again as a sales loss or cash use</label>`:''}</section>`;}).join('')}</div>${timing.collections.enabled&&timing.inventory.enabled?`<label class="uw-checkbox uw-timing-distinct"><input type="checkbox" data-timing-distinct ${timing.distinctReceiptPoolsReviewed?'checked':''}>These two receipt pools do not overlap</label>`:''}`;
}
export function cashTimingImpactHtml(result,money) {
  if(!result?.enabled)return '<p class="uw-fine">No receipt delays selected. Enable a case to test its cash effect.</p>';
  if(!result.ready)return `<p class="uw-data-warning">${esc(result.issues.join(' '))}</p>`;
  return `<div class="uw-timing-result"><strong>${money(result.totalDelayed)} delayed</strong><span>${money(result.recoveryBeyondHorizon)} remains outside the forecast</span></div><table class="uw-table"><thead><tr><th>Month</th><th>Cash before timing change</th><th>Receipt timing impact</th><th>Adjusted cash before debt</th></tr></thead><tbody>${result.impactRows.map(r=>`<tr><td>${esc(r.month)}</td><td>${money(r.baselinePreDebtCash)}</td><td>${money(r.cashDelta)}</td><td>${money(r.adjustedPreDebtCash)}</td></tr>`).join('')}</tbody></table><p class="uw-fine">PO and debt due dates stay unchanged. Recovery enters once, only in the selected month. Weaker-sales gross-contribution adjustments remain separate.</p>`;
}
