-- Shopify Payments payouts + accounting export foundation.
--
-- shopify_payouts: one row per payout (deposit) per store, synced nightly
-- from /shopify_payments/payouts.json with the gross/fee summary that powers
-- the monthly processing-fee journal entry and the deposit register for bank
-- reconciliation. Payout ids are globally unique across Shopify, so the
-- payout_id unique key also dedupes duplicate connections to the same shop.
--
-- accounting_coa_map: per-company chart-of-accounts names used by the
-- Accounting Export page when rendering journal entries. Keys with a
-- {location} placeholder are templates. Seeded with Baseballism's current
-- Google-Sheets account names; editable in the UI.

create table if not exists public.shopify_payouts (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  connection_id uuid references public.shopify_connections(id),
  shop_domain text not null,
  payout_id text not null unique,
  payout_date date not null,
  status text,
  currency text,
  amount_net numeric not null default 0,
  charges_gross numeric not null default 0,
  charges_fee numeric not null default 0,
  refunds_gross numeric not null default 0,
  refunds_fee numeric not null default 0,
  adjustments_gross numeric not null default 0,
  adjustments_fee numeric not null default 0,
  reserved_funds_gross numeric not null default 0,
  reserved_funds_fee numeric not null default 0,
  retried_payouts_gross numeric not null default 0,
  retried_payouts_fee numeric not null default 0,
  synced_at timestamptz,
  sync_batch_id text,
  created_at timestamptz not null default now()
);

create index if not exists shopify_payouts_co_date_idx
  on public.shopify_payouts (company_entity_id, payout_date);
create index if not exists shopify_payouts_shop_date_idx
  on public.shopify_payouts (shop_domain, payout_date);

alter table public.shopify_payouts enable row level security;

-- Clients read their active company's payouts; only the sync (service_role,
-- bypasses RLS) writes.
drop policy if exists shopify_payouts_active_select on public.shopify_payouts;
create policy shopify_payouts_active_select
  on public.shopify_payouts for select to authenticated
  using (company_entity_id = public.active_company_id());

create table if not exists public.accounting_coa_map (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  map_key text not null,
  account_name text not null,
  updated_at timestamptz not null default now(),
  unique (company_entity_id, map_key)
);

alter table public.accounting_coa_map enable row level security;

drop policy if exists accounting_coa_map_active_select on public.accounting_coa_map;
create policy accounting_coa_map_active_select
  on public.accounting_coa_map for select to authenticated
  using (company_entity_id = public.active_company_id());

drop policy if exists accounting_coa_map_active_insert on public.accounting_coa_map;
create policy accounting_coa_map_active_insert
  on public.accounting_coa_map for insert to authenticated
  with check (company_entity_id = public.active_company_id());

drop policy if exists accounting_coa_map_active_update on public.accounting_coa_map;
create policy accounting_coa_map_active_update
  on public.accounting_coa_map for update to authenticated
  using (company_entity_id = public.active_company_id())
  with check (company_entity_id = public.active_company_id());

drop policy if exists accounting_coa_map_active_delete on public.accounting_coa_map;
create policy accounting_coa_map_active_delete
  on public.accounting_coa_map for delete to authenticated
  using (company_entity_id = public.active_company_id());

-- Stamp company on insert like every other company-scoped table.
select public.attach_stamp_company_entity_id_triggers();

-- Baseballism defaults — mirrors the existing Google Sheets journal entries.
insert into public.accounting_coa_map (company_entity_id, map_key, account_name)
values
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'revenue_template',  'In Store Retail Revenue - Shopify ({location})'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'freight',           'Freight Revenue'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'refunds_template',  'Sales Refunds - ({location})'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'discounts',         'COGS - Sales Discounts'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'tax_liability',     'COGS - Sales Tax Liability'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'tax_payable',       'Sales Tax Payable'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'accounts_receivable', 'Accounts Receivable'),
  ('3bd934c9-4cdd-429b-9076-f8f6b45d4eb7', 'processing_fees',   'COGS - Processing Fees')
on conflict (company_entity_id, map_key) do nothing;

-- Server-side bucket aggregation for the Accounting Export page (a month of
-- SKU-level rows is ~50k — aggregate in the DB, not the browser). Security
-- invoker + the invoker verification view keeps company RLS in force.
create or replace function public.accounting_sales_buckets(p_from date, p_to date)
returns table (
  location_tag text,
  location_name text,
  gross numeric,
  discounts numeric,
  refunds numeric,
  shipping numeric,
  taxes numeric,
  total numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    location_tag,
    max(coalesce(location_name, location_tag)) as location_name,
    round(sum(coalesce(total_gross_sales, 0))::numeric, 2) as gross,
    round(sum(coalesce(total_discounts, 0))::numeric, 2) as discounts,
    round(sum(coalesce(total_refunds, 0))::numeric, 2) as refunds,
    round(sum(coalesce(shipping, sum_shipping, 0))::numeric, 2) as shipping,
    round(sum(coalesce(taxes, sum_taxes, 0))::numeric, 2) as taxes,
    round(sum(coalesce(total_sales, sum_total_sales, 0))::numeric, 2) as total
  from public.sales_by_day_verification_v
  where day_date >= p_from and day_date < p_to
  group by location_tag
  order by 8 desc;
$$;

grant execute on function public.accounting_sales_buckets(date, date) to authenticated;
