-- Shopify draft orders sync.
--
-- Root cause of the "MLB wholesale orders missing" gap: Shopify's Orders API
-- (/orders.json, what shopify-sync-core.mjs already pulls into sales_by_day)
-- never includes draft orders — they're a separate resource
-- (/draft_orders.json) that only becomes a real Order once completed/paid in
-- Shopify. Wholesale/rep-built carts and invoiced net-terms sales commonly
-- sit in draft status for days or weeks, so they were invisible to Silo the
-- whole time.
--
-- shopify_draft_orders gives visibility into that pipeline (open,
-- invoice_sent, completed) without touching sales_by_day — once a draft is
-- completed, Shopify auto-creates the real Order and the existing
-- incremental_sales job already picks it up on its own, so folding drafts
-- into sales_by_day directly would double-count. This table is for
-- visibility/reporting on the draft pipeline itself (what's stuck open,
-- what's invoiced but unpaid, how long completion takes), not a sales feed.

create table if not exists public.shopify_draft_orders (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  connection_id uuid references public.shopify_connections(id),
  shop_domain text not null,
  draft_order_id text not null,
  name text,
  status text not null,
  customer_id text,
  customer_email text,
  customer_name text,
  total_price numeric not null default 0,
  subtotal_price numeric not null default 0,
  total_tax numeric not null default 0,
  currency text,
  tags text,
  note text,
  order_id text,
  shopify_created_at timestamptz,
  shopify_updated_at timestamptz,
  invoice_sent_at timestamptz,
  completed_at timestamptz,
  synced_at timestamptz,
  sync_batch_id text,
  created_at timestamptz not null default now(),
  unique (shop_domain, draft_order_id)
);

create index if not exists shopify_draft_orders_co_status_idx
  on public.shopify_draft_orders (company_entity_id, status);
create index if not exists shopify_draft_orders_co_created_idx
  on public.shopify_draft_orders (company_entity_id, shopify_created_at);

alter table public.shopify_draft_orders enable row level security;

-- Clients read their active company's drafts; only the sync (service_role,
-- bypasses RLS) writes.
drop policy if exists shopify_draft_orders_active_select on public.shopify_draft_orders;
create policy shopify_draft_orders_active_select
  on public.shopify_draft_orders for select to authenticated
  using (company_entity_id = public.active_company_id());

-- Let the sync log its runs in the shared sync_jobs table.
alter table public.sync_jobs drop constraint if exists sync_jobs_job_type_check;
alter table public.sync_jobs add constraint sync_jobs_job_type_check
  check (job_type in (
    'test_connection', 'history_import', 'incremental_sales',
    'inventory_snapshot', 'catalog_sync', 'payouts_sync',
    'supermetrics_kpis', 'draft_orders_sync'
  ));
