-- Action Items & Insights: a deterministic rules engine that turns SILO's
-- existing data (sales comp summary, inventory workboard, PO headers,
-- launch calendar/tasks, AR invoices, payment requests) into structured
-- findings, plus storage for a nightly AI-written digest built ONLY from
-- those findings (no reconciliation/tie-out framing — that's an
-- engineering concern, not a business action item).
--
-- compute_silo_insights(company) is the single source of truth for what
-- counts as a finding. The nightly script (scripts/generate-insights.mjs)
-- calls it per company, feeds the JSON to an LLM with an instruction to
-- synthesize ONLY from the given findings (never invent numbers), and
-- stores both the structured findings and the narrative so the UI can
-- always show the verifiable numbers next to the prose.

create table if not exists public.silo_insights_digest (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  generated_at timestamptz not null default now(),
  findings jsonb not null default '[]'::jsonb,
  narrative text,
  model text,
  unique (company_entity_id)
);

alter table public.silo_insights_digest enable row level security;

drop policy if exists silo_insights_digest_active_select on public.silo_insights_digest;
create policy silo_insights_digest_active_select
  on public.silo_insights_digest for select to authenticated
  using (company_entity_id = public.active_company_id());

create or replace function public.compute_silo_insights(p_company_entity_id uuid)
returns table (
  domain text,
  severity text,
  title text,
  detail text,
  metric numeric,
  link_href text
)
language sql
stable
security definer
set search_path = public
as $$

  -- ---- SALES: company-wide day/MTD variance vs prior year, from the
  -- already-anchored (complete-day) comp summary. $500 PY floor keeps a
  -- near-zero base from producing a meaningless "-90%".
  with sales_totals as (
    select
      sum(cur_day_net) as cur_day_net, sum(py_day_net) as py_day_net,
      sum(cur_mtd_net) as cur_mtd_net, sum(py_mtd_net) as py_mtd_net
    from public.sales_verification_store_comp_summary
    where company_entity_id = p_company_entity_id
  ),
  sales_findings as (
    select
      'sales'::text as domain,
      case when day_pct <= -0.25 then 'critical' else 'warning' end as severity,
      'Sales pace down ' || round(abs(day_pct)*100)::text || '% vs last year' as title,
      'Yesterday''s net sales were $' || round(cur_day_net)::text || ' vs $' || round(py_day_net)::text || ' the same day last year.' as detail,
      day_pct as metric,
      '/v2/bi-sales-overview.html' as link_href
    from (select cur_day_net, py_day_net, (cur_day_net - py_day_net) / nullif(py_day_net,0) as day_pct from sales_totals) x
    where py_day_net >= 500 and day_pct <= -0.15
    union all
    select
      'sales', case when mtd_pct <= -0.20 then 'critical' else 'warning' end,
      'Month-to-date sales down ' || round(abs(mtd_pct)*100)::text || '% vs last year',
      'MTD net sales are $' || round(cur_mtd_net)::text || ' vs $' || round(py_mtd_net)::text || ' last year through the same date.',
      mtd_pct, '/v2/bi-sales-overview.html'
    from (select cur_mtd_net, py_mtd_net, (cur_mtd_net - py_mtd_net) / nullif(py_mtd_net,0) as mtd_pct from sales_totals) x
    where py_mtd_net >= 500 and mtd_pct <= -0.10
    union all
    select
      'sales', 'info',
      'Month-to-date sales up ' || round(mtd_pct*100)::text || '% vs last year',
      'MTD net sales are $' || round(cur_mtd_net)::text || ' vs $' || round(py_mtd_net)::text || ' last year — keep an eye on inventory cover for what''s driving it.',
      mtd_pct, '/v2/bi-sales-overview.html'
    from (select cur_mtd_net, py_mtd_net, (cur_mtd_net - py_mtd_net) / nullif(py_mtd_net,0) as mtd_pct from sales_totals) x
    where py_mtd_net >= 500 and mtd_pct >= 0.15
  ),

  -- ---- INVENTORY: best-sellers about to stock out, and dead stock tying
  -- up meaningful cash. Same days_oos<=14 threshold as the Top Sellers
  -- "at risk" KPI, for consistency across the app.
  stockout_risk as (
    select count(*) as n,
           min(days_oos) as worst_days,
           (array_agg(product_title order by days_oos))[1:5] as sample
    from public.inventory_workboard_v
    where company_entity_id = p_company_entity_id
      and coalesce(avg_day_30,0) > 0.5 and coalesce(days_oos, 999) <= 14
  ),
  inventory_findings as (
    select
      'inventory'::text, case when worst_days <= 7 then 'critical' else 'warning' end,
      n::text || ' best-seller' || (case when n=1 then '' else 's' end) || ' at risk of stocking out within 14 days',
      'Includes: ' || array_to_string(sample, ', ') || case when n > 5 then ', and ' || (n-5)::text || ' more.' else '.' end,
      worst_days::numeric, '/v2/bi-top-sellers.html'
    from stockout_risk where n > 0
    union all
    select
      'inventory', 'info',
      dead_count::text || ' SKU' || (case when dead_count=1 then '' else 's' end) || ' with no sales in 60+ days tying up $' || round(dead_value)::text,
      'On-hand inventory with $500+ of value and no recorded sale in the last 60 days — candidates for a markdown or bundle.',
      dead_value, '/v2/inventory.html'
    from (
      select count(*) as dead_count, sum(total_available_quantity * coalesce(retail_price,0)) as dead_value
      from public.inventory_workboard_v
      where company_entity_id = p_company_entity_id
        and total_available_quantity > 0
        and (last_sold_date is null or last_sold_date < current_date - 60)
    ) d
    where dead_value >= 500

  -- ---- PURCHASING: draft POs going stale, and overdue arrivals.
  ),
  purchasing_findings as (
    select
      'purchasing'::text, 'warning'::text,
      n::text || ' draft PO' || (case when n=1 then '' else 's' end) || ' sitting 14+ days without being sent to a factory',
      'Oldest: "' || oldest_name || '" created ' || oldest_days::text || ' days ago. Either send it or close it out.',
      oldest_days::numeric, '/v2/po-report.html'
    from (
      select count(*) as n,
             (array_agg(po_name order by created_at))[1] as oldest_name,
             (extract(day from now() - min(created_at)))::int as oldest_days
      from public.po_headers
      where company_entity_id = p_company_entity_id
        and status = 'Draft' and created_at < now() - interval '14 days'
    ) x
    where n > 0
    union all
    select
      'purchasing', case when max_overdue >= 14 then 'critical' else 'warning' end,
      n::text || ' PO' || (case when n=1 then '' else 's' end) || ' past their expected arrival date',
      'Worst is ' || max_overdue::text || ' days overdue. Follow up with the factory on status.',
      max_overdue::numeric, '/v2/po-report.html'
    from (
      select count(*) as n, max((current_date - expected_arrival_date))::int as max_overdue
      from public.po_headers
      where company_entity_id = p_company_entity_id
        and status not in ('Received','Cancelled','Draft')
        and expected_arrival_date < current_date
    ) x
    where n > 0

  -- ---- PLANNING: launches at risk in the next 2 weeks, overdue open tasks.
  ),
  planning_findings as (
    select
      'planning'::text, case when min_days <= 7 then 'critical' else 'warning' end,
      n::text || ' launch' || (case when n=1 then '' else 'es' end) || ' in the next 14 days not marked ready',
      'Soonest: "' || soonest_title || '" in ' || min_days::text || ' day' || (case when min_days=1 then '' else 's' end) || '.',
      min_days::numeric, '/v2/launch-calendar.html'
    from (
      select count(*) as n,
             min(launch_date - current_date) as min_days,
             (array_agg(title order by launch_date))[1] as soonest_title
      from public.launch_calendar
      where company_entity_id = p_company_entity_id
        and launch_date between current_date and current_date + 14
        and coalesce(launch_readiness,'not_reviewed') <> 'ready'
    ) x
    where n > 0
    union all
    select
      'planning', 'warning',
      n::text || ' launch task' || (case when n=1 then '' else 's' end) || ' overdue',
      'Open tasks past their due date across active launches.',
      n::numeric, '/v2/tasks.html'
    from (
      select count(*) as n
      from public.launch_tasks
      where company_entity_id = p_company_entity_id
        and status = 'open' and due_date < current_date
    ) x
    where n > 0

  -- ---- AR: aging receivables. ar_invoices/ar_customers carry
  -- company_entity_id directly even though the reader views don't expose it.
  ),
  ar_findings as (
    select
      'ar'::text, 'critical'::text,
      '$' || round(total_90plus)::text || ' in receivables 90+ days past due',
      'Across ' || cust_count::text || ' customer' || (case when cust_count=1 then '' else 's' end) || '. Worst: ' || worst_name || ' ($' || round(worst_amt)::text || ').',
      total_90plus, '/v2/baseballismwholesale.html'
    from (
      select sum(i.open_amount) as total_90plus,
             count(distinct i.customer_id) as cust_count,
             (array_agg(c.customer_name order by i.open_amount desc))[1] as worst_name,
             max(i.open_amount) as worst_amt
      from public.ar_invoices i join public.ar_customers c on c.id = i.customer_id
      where i.company_entity_id = p_company_entity_id
        and i.is_open and i.aging_bucket = '90+'
    ) x
    where total_90plus >= 1000
    union all
    select
      'ar', 'warning',
      '$' || round(total_6190)::text || ' in receivables 61-90 days past due',
      'Getting close to 90 days — worth a reminder before it ages further.',
      total_6190, '/v2/baseballismwholesale.html'
    from (
      select sum(open_amount) as total_6190
      from public.ar_invoices
      where company_entity_id = p_company_entity_id and is_open and aging_bucket = '61-90'
    ) x
    where total_6190 >= 1000

  -- ---- AP: overdue and large-pending payment requests.
  ),
  ap_findings as (
    select
      'ap'::text, 'critical'::text,
      n::text || ' payment request' || (case when n=1 then '' else 's' end) || ' overdue, totaling $' || round(total)::text,
      'Still open (not completed) past their due date.',
      total, '/v2/request_manager.html'
    from (
      select count(*) as n, sum(amount_due) as total
      from public.payment_requests
      where company_entity_id = p_company_entity_id
        and coalesce(completed,false) = false and due_date < current_date
    ) x
    where n > 0
    union all
    select
      'ap', 'warning',
      n::text || ' payment request' || (case when n=1 then '' else 's' end) || ' over $5,000 awaiting action',
      'Not yet marked complete.',
      total, '/v2/request_manager.html'
    from (
      select count(*) as n, sum(amount_due) as total
      from public.payment_requests
      where company_entity_id = p_company_entity_id
        and coalesce(completed,false) = false and amount_due >= 5000
    ) x
    where n > 0
  )

  select * from sales_findings
  union all select * from inventory_findings
  union all select * from purchasing_findings
  union all select * from planning_findings
  union all select * from ar_findings
  union all select * from ap_findings;
$$;

-- SECURITY DEFINER with a caller-supplied company id — only the nightly
-- job (service_role) may call this directly. End users never call it; they
-- read the pre-computed, RLS-scoped silo_insights_digest row instead.
revoke execute on function public.compute_silo_insights(uuid) from public, anon, authenticated;
grant execute on function public.compute_silo_insights(uuid) to service_role;
