-- Ask SILO: teach the schema catalog the three caveats a live SEO answer
-- got wrong on 2026-09-08.
--
-- The answer concluded eight Shopify collections "don't exist" because
-- they were absent from a LIMIT 30 query over shopify_landing_pages_daily.
-- Every step of that was wrong in a way the catalog could have prevented:
--
--   * the table is a TOP-250-PER-DAY slice, not the full tail. Measured
--     the same day: 10,553 of 10,763 rows carry is_truncated = true, so
--     98% of days hit the cap and dropped whatever ranked 251st down.
--   * its history began 2026-07-28, so the 60-day window asked for was
--     really 42 days.
--   * it records landing SESSIONS. A collection with no landing traffic
--     is absent from it whether or not the collection exists -- and SILO
--     stores no registry of collections at all, so nothing here can
--     answer an existence question either way.
--
-- The old description already warned against SUMMING this table ("must
-- never be summed as total sessions"), and that warning worked -- the
-- answer did not sum it. It said nothing about NEGATIVE claims, and the
-- model happily made one. A caveat only covers the failure it names.
--
-- Same answer also read our campaign-grain Google Ads sync as evidence
-- that Google Ads offers no category-level reporting. It offers plenty;
-- scripts/lib/ad-platforms-sync-core.mjs just queries `FROM campaign`
-- and nothing else. That distinction (our grain vs. the provider's
-- capability) now appears both here and in the edge function's prompt.
--
-- Descriptions only -- no schema change, no policy change. Column lists
-- stay auto-generated by refresh_chat_schema_catalog(), which preserves
-- description/keywords across refreshes.

update public.silo_chat_schema_catalog
set description =
  'Sessions and funnel counts per landing page path per day, from ShopifyQL. '
  'TOP-N SLICE, NOT A COMPLETE LIST: only about the top 250 paths per day are '
  'stored (is_truncated marks a day that hit the cap; rank_in_day gives the '
  'position), so it must never be summed as total sessions -- use '
  'shopify_sessions_daily for totals. ABSENCE IS NOT NONEXISTENCE: a path '
  'missing here had no recorded landing traffic in the retained slice, which '
  'is NOT evidence the page or collection does not exist. SILO stores no '
  'registry of Shopify collections/pages/URLs, so no query can currently '
  'confirm a page exists -- say so rather than inferring it from this table. '
  'Check min(day_date) before describing a window: history is far shorter than '
  'the sync window suggests. Good for which pages get traffic and which convert.',
    updated_at = now()
where relname = 'shopify_landing_pages_daily';

update public.silo_chat_schema_catalog
set description =
  'Daily ad spend/revenue by platform (google_ads, meta_ads, tiktok_ads, ga4), '
  'CAMPAIGN-level. The authoritative ledger for spend. GRAIN IS OURS, NOT THE '
  'PROVIDER''S: Google Ads rows stop at campaign because the sync queries only '
  '`FROM campaign` -- ad groups, keywords, search terms, PMax asset groups and '
  'shopping product performance all exist in the Google Ads account under the '
  'access already granted and are simply not ingested. Never report a grain we '
  'do not sync as one the platform does not offer. GA4 rows are not campaigns '
  'at all: campaign_name carries the GA4 default channel group (Organic Search, '
  'Paid Social, Email, ...), so ga4 + campaign_name = ''Organic Search'' is the '
  'only organic-search signal SILO has -- session VOLUME at channel level, never '
  'per-query, per-page or ranking data, and never attributable to a specific '
  'search query.',
    updated_at = now()
where relname = 'marketing_kpis_daily';

update public.silo_chat_schema_catalog
set description = coalesce(description, '') ||
  ' RANKS SALES, NOT AVAILABILITY: says nothing about whether a product is in '
  'stock, still published, or has a complete size run today. Before recommending '
  'anything here to feature or promote, join current stock from '
  'inventory_on_hand_current_v / inventory_workboard_v (variant_title carries the '
  'size).',
    updated_at = now()
where relname = 'sales_by_product_title_daily_v'
  and description not like '%RANKS SALES, NOT AVAILABILITY%';
