-- Order-level and line-item-level Shopify sales facts.
--
-- sales_by_day (ordersToSalesRows in scripts/lib/shopify-sync-core.mjs)
-- collapses every order's line items into per-SKU/day/location aggregate
-- rows -- that's the shape all existing reporting depends on, and it is
-- untouched by this migration. What that collapse discards is the order
-- boundary itself: which line items belonged to the same order, what sales
-- channel the order came through (Shopify's source_name field -- "web",
-- "pos", or an opaque app id/slug for third-party channels like TikTok or
-- Faire), and who the customer was.
--
-- shopify_orders / shopify_order_lines capture that pre-collapse shape in
-- parallel, from the exact same order objects already fetched for
-- sales_by_day -- no extra Shopify API calls (see upsertOrderFacts in
-- shopify-sync-core.mjs, called from the same order loops as
-- ordersToSalesRows).
--
-- Unlike sales_by_day's append/delta model (needed because day-aggregates
-- can't be patched in place), these are plain upserts keyed on Shopify's
-- own ids: an order or line item row is simply overwritten with its
-- current state on every sync that touches it, so cancellations/refunds/
-- edits self-correct without delta bookkeeping. Line items removed from an
-- edited order are handled by deleting all line rows for the touched order
-- ids before reinserting the current set.

create table if not exists public.shopify_orders (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  connection_id uuid references public.shopify_connections(id),
  shop_domain text not null,
  order_id text not null,
  order_number text,
  source_name text,
  financial_status text,
  fulfillment_status text,
  cancelled_at timestamptz,
  cancel_reason text,
  customer_id text,
  customer_email text,
  customer_name text,
  currency text,
  subtotal_price numeric not null default 0,
  total_discounts numeric not null default 0,
  total_tax numeric not null default 0,
  total_shipping numeric not null default 0,
  total_price numeric not null default 0,
  tags text,
  location_id text,
  line_item_count integer not null default 0,
  shopify_created_at timestamptz,
  shopify_processed_at timestamptz,
  shopify_updated_at timestamptz,
  synced_at timestamptz,
  sync_batch_id text,
  created_at timestamptz not null default now(),
  unique (shop_domain, order_id)
);

create index if not exists shopify_orders_co_created_idx
  on public.shopify_orders (company_entity_id, shopify_created_at);
create index if not exists shopify_orders_co_source_idx
  on public.shopify_orders (company_entity_id, source_name);

alter table public.shopify_orders enable row level security;

drop policy if exists shopify_orders_active_select on public.shopify_orders;
create policy shopify_orders_active_select
  on public.shopify_orders for select to authenticated
  using (company_entity_id = public.active_company_id());

create table if not exists public.shopify_order_lines (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  connection_id uuid references public.shopify_connections(id),
  shop_domain text not null,
  order_id text not null,
  line_item_id text not null,
  sku text,
  product_id text,
  variant_id text,
  title text,
  variant_title text,
  quantity integer not null default 0,
  price numeric not null default 0,
  discount_allocated numeric not null default 0,
  tax_allocated numeric not null default 0,
  fulfillable_quantity integer not null default 0,
  fulfillment_status text,
  gift_card boolean not null default false,
  vendor text,
  product_type text,
  synced_at timestamptz,
  sync_batch_id text,
  created_at timestamptz not null default now(),
  unique (shop_domain, order_id, line_item_id)
);

create index if not exists shopify_order_lines_co_order_idx
  on public.shopify_order_lines (company_entity_id, order_id);
create index if not exists shopify_order_lines_co_sku_idx
  on public.shopify_order_lines (company_entity_id, sku);

alter table public.shopify_order_lines enable row level security;

drop policy if exists shopify_order_lines_active_select on public.shopify_order_lines;
create policy shopify_order_lines_active_select
  on public.shopify_order_lines for select to authenticated
  using (company_entity_id = public.active_company_id());

-- Editable raw source_name -> human channel name map. Shopify's source_name
-- is frequently an opaque app id/slug for third-party channels rather than a
-- clean "TikTok"/"Faire" string, so this needs to be admin-correctable in
-- the Integrations UI rather than hardcoded here -- same pattern as
-- accounting_coa_map.
create table if not exists public.shopify_channel_map (
  id bigint generated by default as identity primary key,
  company_entity_id uuid not null references public.entities(id),
  source_name text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_entity_id, source_name)
);

alter table public.shopify_channel_map enable row level security;

drop policy if exists shopify_channel_map_select on public.shopify_channel_map;
create policy shopify_channel_map_select
  on public.shopify_channel_map for select using (company_entity_id = active_company_id());

drop policy if exists shopify_channel_map_write on public.shopify_channel_map;
create policy shopify_channel_map_write
  on public.shopify_channel_map for all
  using    (company_entity_id = active_company_id() and is_admin_user())
  with check (company_entity_id = active_company_id() and is_admin_user());

drop trigger if exists set_updated_at on public.shopify_channel_map;
create trigger set_updated_at before update on public.shopify_channel_map
  for each row execute function public.set_updated_at();

-- Attaches (or refreshes) the stamp_company_entity_id BEFORE INSERT trigger
-- on every public table with a company_entity_id column, including the
-- three above -- lets shopify_channel_map inserts from the Integrations UI
-- omit company_entity_id and have it filled from active_company_id().
select public.attach_stamp_company_entity_id_triggers();

create or replace view public.shopify_orders_v
with (security_invoker = true) as
select
  o.*,
  coalesce(m.display_name, o.source_name) as resolved_channel_name
from public.shopify_orders o
left join public.shopify_channel_map m
  on m.company_entity_id = o.company_entity_id
  and m.source_name = o.source_name;

revoke all on public.shopify_orders_v from anon;
grant select on public.shopify_orders_v to authenticated;
