-- Company document identity: what a tenant's outbound documents say about it.
--
-- /v2/po-builder.html's vendor PDF printed "Baseballism Inc.", a Beaverton
-- street address and a named buyer with a phone number as literals in the
-- page -- so a purchase order generated by ANY tenant went to its factory
-- under Baseballism's name and ship-to. Nothing per-company held those facts:
-- entities carries a title, company_settings a timezone and a currency, and
-- company_notification_contacts a reply address per purpose. The PDF needs a
-- legal name, a ship-to block and a purchasing contact, so those live here,
-- on company_settings, which already has the right shape: one row per company,
-- readable by any member (company_settings_select) and writable only by a
-- membership owner_admin (company_settings_update). No policy changes.
--
-- Every column is nullable. A blank is rendered by the page as "not
-- configured" and named in a confirm before the PDF opens -- never silently
-- as Baseballism's, and never invented. The purchasing contact is optional by
-- design: blank means "whoever generates the PO", read from their profile.
--
-- Idempotent: add-if-not-exists, and the Baseballism seed writes only where
-- the column is still null, so a later edit on the settings page is never
-- overwritten by a re-run of apply_all_post_merge.sql.

alter table public.company_settings
  add column if not exists legal_name               text,
  add column if not exists address_line1            text,
  add column if not exists address_line2            text,
  add column if not exists city                     text,
  add column if not exists region                   text,
  add column if not exists postal_code              text,
  add column if not exists country                  text,
  add column if not exists phone                    text,
  add column if not exists purchasing_contact_name  text,
  add column if not exists purchasing_contact_phone text,
  add column if not exists purchasing_contact_email text;

comment on column public.company_settings.legal_name is
  'Name printed on outbound documents (PO Builder vendor PDF header, ship-to and footer). Falls back to entities.title when null; distinct from it because the trading name and the name on a purchase order differ ("Baseballism" vs "Baseballism Inc.").';
comment on column public.company_settings.address_line1 is
  'Ship-to address printed on the PO Builder vendor PDF, with address_line2, city, region, postal_code and country. Null means not configured; the page says so rather than printing another tenant''s address.';
comment on column public.company_settings.purchasing_contact_name is
  'Buyer contact printed on the PO Builder vendor PDF, with purchasing_contact_phone and purchasing_contact_email. Optional: when all three are null the page prints the profile of whoever generates the PO.';

-- Baseballism keeps exactly what its PDF printed before this migration.
-- Written only where null, so the settings page stays the source of truth.
update public.company_settings cs
   set legal_name               = coalesce(cs.legal_name, 'Baseballism Inc.'),
       address_line1            = coalesce(cs.address_line1, '11035 SW 11th Street'),
       address_line2            = coalesce(cs.address_line2, 'Building B, Suite 290'),
       city                     = coalesce(cs.city, 'Beaverton'),
       region                   = coalesce(cs.region, 'OR'),
       postal_code              = coalesce(cs.postal_code, '97005'),
       purchasing_contact_name  = coalesce(cs.purchasing_contact_name, 'Chris Clements'),
       purchasing_contact_phone = coalesce(cs.purchasing_contact_phone, '(831) 383-8283')
  from public.entities e
 where e.id = cs.company_entity_id
   and e.entity_key = 'baseballism'
   and (cs.legal_name is null or cs.address_line1 is null or cs.purchasing_contact_name is null);

-- Ask SILO's schema map lists company_settings' columns; keep it current.
select public.refresh_chat_schema_catalog();
