-- Redo returns integration, phase 1: webhook-driven ingestion of Redo return
-- data (refund / exchange / store-credit dollar amounts) so the BI-vs-Shopify
-- variance noted in docs/ops/bugs.md ("Redo exchange/store-credit returns
-- with $0 refund subtotals") can be reconciled against real numbers instead
-- of inferred from Shopify's own refund records, which only ever see the
-- `refund` slice of a Redo return -- exchanges and store credit settle
-- entirely inside Redo.
--
-- Ingestion is push-based: Redo's "Return event" webhook POSTs the full
-- return object (same shape as GET /returns/{id}) on every status change,
-- delivered in order per return, retried on non-2xx. That's simpler and
-- more current than polling, so there is no GitHub Action here -- the
-- redo-webhook edge function (deployed separately, see
-- docs/ops/redo-integration.md) is the entire pipeline.

-- redo_connections: one row per company. api_secret is the REDO_API_SECRET
-- (Bearer token Redo issues for calling api.getredo.com -- not used by the
-- webhook path itself, kept for a future GET /returns/{id} backfill/verify
-- script). webhook_secret is generated by SILO and pasted into Redo's
-- per-store webhook config; the edge function checks incoming
-- `Authorization: Bearer <webhook_secret>` against this column to confirm
-- the request actually came from that company's Redo store.
create table if not exists public.redo_connections (
  id uuid primary key default gen_random_uuid(),
  company_entity_id uuid not null references public.entities(id) on delete cascade,
  display_name text,
  is_active boolean not null default true,

  api_secret text,
  webhook_secret text,

  last_event_at timestamptz,
  last_event_type text,

  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

-- One Redo store account per company (unlike ad_platform_connections, which
-- allows multiple ad accounts per platform) -- Redo's API secret already
-- scopes to a single store, so a second row would just be a duplicate.
create unique index if not exists idx_redo_connections_company
  on public.redo_connections (company_entity_id);

alter table public.redo_connections enable row level security;
revoke all on public.redo_connections from anon;

drop policy if exists redo_connections_active_select on public.redo_connections;
create policy redo_connections_active_select
  on public.redo_connections for select
  to authenticated
  using (company_entity_id = public.active_company_id());

drop policy if exists redo_connections_admin_write on public.redo_connections;
create policy redo_connections_admin_write
  on public.redo_connections for all
  to authenticated
  using (company_entity_id = public.active_company_id() and public.is_admin_user())
  with check (company_entity_id = public.active_company_id() and public.is_admin_user());

drop trigger if exists stamp_created_by on public.redo_connections;
create trigger stamp_created_by
  before insert on public.redo_connections
  for each row execute function public.stamp_created_by();

-- redo_returns: one row per Redo return, upserted on every webhook event for
-- that return's lifetime (open -> ... -> complete/rejected/deleted). `raw`
-- keeps the full payload from the latest event so fields not yet
-- columnized (line items, shipment tracking, tags, notes) aren't lost.
create table if not exists public.redo_returns (
  id uuid primary key default gen_random_uuid(),
  company_entity_id uuid not null references public.entities(id) on delete cascade,

  redo_return_id text not null,
  redo_order_id text,
  shopify_order_name text,
  shopify_order_id text,

  return_type text,
  status text,
  compensation_methods text[] not null default '{}',

  refund_amount numeric(12,2) not null default 0,
  exchange_amount numeric(12,2) not null default 0,
  store_credit_amount numeric(12,2) not null default 0,
  charge_amount numeric(12,2) not null default 0,
  shipping_fee_amount numeric(12,2) not null default 0,
  currency text not null default 'USD',

  last_event_type text,
  redo_created_at timestamptz,
  redo_updated_at timestamptz,
  raw jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_redo_returns_company_return
  on public.redo_returns (company_entity_id, redo_return_id);
create index if not exists idx_redo_returns_company_order_name
  on public.redo_returns (company_entity_id, shopify_order_name);
create index if not exists idx_redo_returns_company_shopify_order
  on public.redo_returns (company_entity_id, shopify_order_id);
create index if not exists idx_redo_returns_company_status
  on public.redo_returns (company_entity_id, status);

alter table public.redo_returns enable row level security;
revoke all on public.redo_returns from anon;

-- Read-only to the app: only the service-role webhook edge function writes
-- this table (same trust model as marketing_kpis_daily / ad_platform sync
-- writes -- no authenticated insert/update/delete policy).
drop policy if exists redo_returns_active_select on public.redo_returns;
create policy redo_returns_active_select
  on public.redo_returns for select
  to authenticated
  using (company_entity_id = public.active_company_id());
